config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'users/session/new' => 'sessions#new', as: :login
  post 'users/session/create' => 'sessions#create'
  get 'users/session/clear' => 'sessions#destroy', as: :logout

  resources :users

  resources :decks

  get 'decks/upload/new' => 'decks#new_upload', as: :upload
  post 'decks/upload/create' => 'decks#upload'

end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :deck

	validates :question, presence: true
	validates :answer, presence: true
	validates :deck_id, presence: true
end

app/models/deck.rb
class Deck < ActiveRecord::Base
	has_many :cards
	has_many :users
	belongs_to :author, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :decks
  has_many :authored_decks, class_name: "Deck", foreign_key: "author_id"

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/models/user_deck.rb
class UserDeck < ActiveRecord::Base
	belongs_to :deck
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

	def create
		@deck = Deck.new(deck_params)
		if @deck.save
			UserDeck.create(user_id: session[:user], deck_id: @deck.id)
			redirect_to user_path(session[:user])
		end
	end

	def new_upload
		@deck = Deck.new
		render 'upload'
	end

	def upload
		upload = File.readlines(params[:deck][:deck].tempfile)
		deck = Deck.create(title: params[:deck][:title], description: params[:deck][:description], private?: params[:deck][:private], author: User.find(session[:user]))
		UserDeck.create(user_id: session[:user], deck_id: deck.id)
		card_set = []
		upload.each do |line| 
			card_set << line.split(",") 
		end
		card_set.each do |card|
			Card.create(question: card[0], answer: card[1], option: card[2], deck_id: deck.id)
		end
		redirect_to user_path(session[:user])
	end

	private

		def deck_params
			params.require(:deck).permit(:title, :description, :deck_image, :deck, :private?)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@session = User.new
		render 'new'	
	end

	def create
		@user = User.find_by_email(params[:username_or_email]) || User.find_by_username(params[:username_or_email])
		if @user && @user.authenticate(params[:password])
			session[:user] = @user.id
			redirect_to user_path(@user.id)
		elsif @user
			@error = "Incorrect password"
			render 'new'
		else
			@error = "Invalid username or email"
			render 'new'
		end
	end

	def destroy
		session.clear
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		user = User.find(params[:id])
		@deck = Deck.new
		@decks = UserDeck.where(user_id: params[:id])
		render 'show'
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if User.find_by_email(params[:user][:email])
			@error = "Email has already been taken"
			render 'new'
		elsif User.find_by_username(params[:user][:username])
			@error = "Username has already been taken"
			render 'new'
		elsif @user.save
			session[:user] = @user.id
			redirect_to user_path(@user.id)
		end
	end

	def destroy
		# <%= link_to 'delete account', user_path(current_user.id), :class => 'user-options-item', method: :delete, data: { confirm: "Are you sure you want to permanently delete your account? We will miss you." } %>
	end

	private

		def user_params
			params.require(:user).permit(:first_name, :last_name, :username, :email, :password)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		unless session[:user] == nil
			redirect_to user_path(session[:user])
		else
			render 'index'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@user ||= User.find(session[:user]) if session[:user]
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def first_time?
		user = User.find(session[:user]).first_time?
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/decks/new.html.erb
<h2>New Deck</h2>

<div class="decks-background">
  <div class="decks-image"></div>
  <%= form_for @deck do |f| %>
  	<%= f.text_field :title, :required => true %>
  	<%= f.text_area :description, :size => "60x12", :required => true  %>
  	<%= f.file_field :deck_image, :accept => "image/*" %>
  	<%= f.file_field :deck, :accept => "text/csv" %>
  	<%= f.select :private?, [['Public', 1], ['Private', 2]] %>
  	<%= f.submit "Upload Deck" %>
  <% end %>
</div>

app/views/decks/upload.html.erb
<h2>Upload Deck</h2>
<p class="decks-instructions">You can upload a deck using a CSV file or Excel spreadsheet. The format is:</p>
<ol class="decks-instructions">
	<li>Column 1 - Question</li>
	<li>Column 2 - Answer</li>
	<li>Column 3 - Option (use the option slot for hints or to create dynamic multi-use playing decks)</li>
</ol>

<div class="decks-background">
  <div class="decks-form-upload">
	  <%= form_for @deck do |f| %>
	  	<%= f.label :title, :class =>"upload-form-label" %><br>
	  	<%= f.text_field :title, :required => true %><br>
	  	<%= f.label :description, :class =>"upload-form-label" %><br>
	  	<%= f.text_area :description, :size => "60x12", :required => true  %><br>
	  	<%= f.label :deck_image, :class =>"upload-form-label" %>
	  	<%= f.file_field :deck_image, :accept => "image/*" %>
	  	<%= f.label :deck_upload, :class =>"upload-form-label" %>
	  	<%= f.file_field :deck, :accept => "text/csv" %>
	  	<%= f.label :make_your_deck_private, :class =>"upload-form-label" %>
	  	<%= f.select :private?, [['Public', 1], ['Private', 2]] %><br>
	  	<%= f.submit "Upload Deck" %>
	  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>smartcards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Sign up</h2>

<div class="registration">

  <%= form_for @user, url: { action: 'create'}, html: {class: 'registration-signup-form' } do |f| %>
  	<%= f.label :first_name, :class =>"form-label" %>
  	<%= f.text_field :first_name, :class => "form-input" %><br>
  	<%= f.label :last_name, :class =>"form-label" %>
  	<%= f.text_field :last_name, :class => "form-input" %><br>
  	<%= f.label :email, :class =>"form-label" %>
  	<%= f.email_field :email, :required => true, :class => "form-input" %><br>
  	<%= f.label :username, :class =>"form-label" %>
  	<%= f.text_field :username,  :required => true, :class => "form-input" %><br>
  	<%= f.label :password, :class =>"form-label" %>
  	<%= f.password_field :password,  :required => true, :class => "form-input" %><br>
  	<%= f.submit "sign up", :class => "registration-signup-btn" %>
  	<% if @error %>
    	<p class="registration-errors"><%= @error %></p>
  	<% end %>
  <% end %>

  <div class="registration-text-field">
    <h6>smartcards is a flashcard app. Join smartcards to contribute to the smartcard community and compete with other members. smartcards will keep track of your progress and map out your personal growth.</h6> <span>Register for a new smartcard account and start your learning.</span>
  </div>
  
  <%= link_to 'log in',  login_path, :class => "registration-login-btn" %>

</div>

app/views/users/show.html.erb
<% if current_user %>
	<div class="user-info">
		<div class="user-logo-icon"></div>
		<div class="user-credentials">
			<p class="user-credentials-text"><%= current_user.first_name %> <%= current_user.last_name %></p>
			<p class="user-credentials-text">Username: <%= current_user.username %></p>
			<p class="user-credentials-text">Email: <%= current_user.email %></p>
			<ul class="user-options">
				<li class='user-options-item'><%= link_to 'user preferences', edit_user_path(current_user), :class => 'user-options-item' %></li>
				<li class='user-options-item'><%= link_to 'log out', logout_path, :class => "user-options-item" %></li>
			</ul>
		</div>
		<div class='user-new-deck'>new deck</div>
		<%= link_to 'upload deck', upload_path, :class => 'user-upload-deck' %>
	</div>
	<div class="user-played-decks">
		<% @decks.each do |deck| %>
			<div class="user-deck">
				<%= deck %>
			</div>
		<% end %>
	</div>
	<div class="modal-screen"></div>
	<div class="user-deck-modal">
		<%= form_for @deck do |f| %>
		<%= f.label :title, :class =>"upload-form-label" %><br>
	  	<%= f.text_field :title, :required => true, :class => "deck-modal-text-field" %><br>
	  	<%= f.label :description, :class =>"upload-form-label" %><br>
	  	<%= f.text_area :description, :size => "60x12", :required => true  %><br>
	  	<%= f.label :deck_image, :class =>"upload-form-label" %>
	  	<%= f.file_field :deck_image, :accept => "image/*" %>
	  	<%= f.label :make_your_deck_private, :class =>"upload-form-label" %>
	  	<%= f.select :private?, [['Public', 1], ['Private', 2]] %><br>
	  	<%= f.submit "Create Deck" %>
		<% end %>
	</div>
<% end %>

app/views/welcome/index.html.erb
<div class="logo-back1"></div>
<div class="logo-back2"></div>

<div class="welcome">
	<h1 class="logo-text">smartcards</h1>
	<div class="logo"></div>
	<%= link_to 'new', new_user_path, :class => "btn btn-signup" %>
	<%= link_to 'log in',  login_path, :class => "btn btn-signin" %>
</div>

<div class="welcome-context">
	<%= image_tag "intro.png", :class => "img-intro" %>
	<div class="introduction">
		<span>Learn efficiently. Maximize your retention.</span> smartcards is a flashcard app designed to help you retain information with more accuracy. By processing the results of each smartcard game, tailoring the flashcard distribution, and offering multiple smartcard games to help reinforce your knowledge of the topic and solidify nuances.
	</div>
	<div class="instructions">
		<div class="instruction-partition">
			<h2 class="instruction-text">Create an Account</h2>
			<%= image_tag "user.png", :class => "img-user" %>
		</div>
		<div class="instruction-partition">
			<h2 class="instruction-text">Make your Deck</h2>
			<%= image_tag "questions.png", :class => "img-questions" %>
		</div>
		<div class="instruction-partition">
			<h2 class="instruction-text">Choose your game</h2>
			<%= image_tag "choices.png", :class => "img-choices" %>
		</div>
		<div class="instruction-partition">
			<h2 class="instruction-text">Track your progress</h2>
			<%= image_tag "progress.png", :class => "img-progress" %>
		</div>
	</div>
</div>